#!/usr/bin/env python3
"""Pre-publication checks for the release tree.

Usage:
    python tools/validate_release.py [--root .] [--bundle bundle]

Checks
  1. hygiene   no absolute server paths, e-mail addresses, private notes,
               or files larger than the GitHub-safe limit in the git tree
  2. bundle    every file listed in bundle/SHA256SUMS exists and matches,
               and holds no server paths or e-mail addresses
  3. results   headline numbers regenerated by `make figures` match
               tools/expected_numbers.tsv (skipped if the table is absent)

Exit status is non-zero if any check fails.
"""
import argparse
import csv
import hashlib
import re
import subprocess
import sys
import tempfile
from pathlib import Path

MAX_BYTES = 50 * 1024 * 1024
TEXT_SUFFIXES = {".R", ".Rmd", ".py", ".sh", ".md", ".cff", ".config", ".csv",
                 ".tsv", ".txt", ".yml", ".yaml", ".json", ".html", "", ".mk"}
FORBIDDEN = [
    (re.compile(r"/(data|home)/bchick"), "absolute server path"),
    (re.compile(r"[A-Za-z0-9._%+-]+@(salk\.edu|gmail\.com)"), "e-mail address"),
    (re.compile(r"\b(claude|anthropic)\b", re.I), "private tooling note"),
    (re.compile(r"\b(thesis|dissertation)\b|\bAct [0-4]\b", re.I), "internal project note"),
]
FORBIDDEN_FILES = {"CLAUDE.md", "claude_code_prompt.md", "PROJECT_AUDIT.md", "TODO.md"}


def tracked_files(root):
    """Files git would commit: tracked ones, or (outside a repository) every
    file not excluded by .gitignore, found through a throwaway git dir."""
    def ls(*cmd):
        return subprocess.run(["git", *cmd], cwd=root, check=True,
                              capture_output=True, text=True).stdout.splitlines()
    if (root / ".git").exists():
        return [root / f for f in ls("ls-files")]
    with tempfile.TemporaryDirectory() as gd:
        ls("--git-dir", gd, "init", "-q")
        out = ls("--git-dir", gd, "--work-tree", str(root),
                 "ls-files", "--others", "--exclude-standard")
    return [root / f for f in out]


def check_hygiene(root):
    errors = []
    for f in tracked_files(root):
        if not f.is_file():  # tracked but deleted in the working tree
            continue
        rel = f.relative_to(root)
        if f.name in FORBIDDEN_FILES:
            errors.append(f"{rel}: file must not be released")
        size = f.stat().st_size
        if size > MAX_BYTES:
            errors.append(f"{rel}: {size / 1e6:.0f} MB exceeds {MAX_BYTES / 1e6:.0f} MB")
        if f.suffix not in TEXT_SUFFIXES or size > 5 * MAX_BYTES or rel.name == "validate_release.py":
            continue
        text = f.read_text(errors="ignore")
        for pat, what in FORBIDDEN:
            for m in pat.finditer(text):
                line = text.count("\n", 0, m.start()) + 1
                errors.append(f"{rel}:{line}: {what} ({m.group(0)})")
    return errors


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def check_bundle(root, bundle):
    """SHA256SUMS lists repository-relative paths (as unpacked by fetch_data.sh)."""
    sums = bundle / "SHA256SUMS"
    if not sums.exists():
        return [f"{sums}: missing (run `make fetch-data`)"]
    errors = []
    for line in sums.read_text().splitlines():
        digest, name = line.split(maxsplit=1)
        f = root / name.lstrip("*")
        if not f.exists():
            errors.append(f"{name}: missing")
        elif sha256(f) != digest:
            errors.append(f"{name}: checksum mismatch")
        else:
            # bundle files are public too: no server paths or e-mail addresses
            text = f.read_bytes().decode(errors="ignore")
            for pat, what in FORBIDDEN[:2]:
                if pat.search(text):
                    errors.append(f"{name}: {what} ({pat.search(text).group(0)})")
    return errors


def check_results(root):
    table = root / "tools" / "expected_numbers.tsv"
    if not table.exists():
        return []
    errors = []
    with open(table) as fh:
        for row in csv.DictReader(fh, delimiter="\t"):
            f = root / row["file"]
            if not f.exists():
                errors.append(f"{row['file']}: missing (run `make figures`)")
                continue
            with open(f) as rf:
                rows = list(csv.DictReader(rf))
            hit = [r for r in rows if all(r.get(k) == v for k, v in
                   (kv.split("=", 1) for kv in row["match"].split(";")))]
            if len(hit) != 1:
                errors.append(f"{row['file']}: {len(hit)} rows match {row['match']}")
            elif hit[0][row["column"]] != row["expected"]:
                errors.append(f"{row['file']} [{row['match']}] {row['column']}: "
                              f"{hit[0][row['column']]} != expected {row['expected']}")
    return errors


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--root", default=".")
    ap.add_argument("--bundle", default="bundle")
    ap.add_argument("--skip", nargs="*", default=[], choices=["hygiene", "bundle", "results"])
    args = ap.parse_args()
    root = Path(args.root).resolve()
    checks = {"hygiene": lambda: check_hygiene(root),
              "bundle": lambda: check_bundle(root, root / args.bundle),
              "results": lambda: check_results(root)}
    failed = False
    for name, fn in checks.items():
        if name in args.skip:
            print(f"[skip] {name}")
            continue
        errs = fn()
        print(f"[{'FAIL' if errs else ' ok '}] {name}")
        for e in errs:
            print("   ", e)
        failed |= bool(errs)
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
